send_job:
  before_script:
    - apt-get update -qq && apt-get install -y -qq software-properties-common
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - echo "install nodejs"
    - apt-get update -qq && apt-get install -y -qq nodejs
    - export TZ='Asia/Shanghai' # 更改时区
    #- export bdurl="http://data.zz.baidu.com/urls?site=www.latelee.org&token="${bdtoken}
    - npm install hexo-cli -g
    - npm install # 安装hexo及插件
  script:
    - hexo clean # 清除
    - hexo g # 生成

  after_script:
    - echo "after script..."
    - cd ./public
    - git init
    - git config user.name  "CST Studio"
    - git config user.email "cst@cststudio.com.cn"
    - git add .
    - git commit -m "CI auto update"
    - git push --force --quiet "https://${GitlabToken}@github.com/cststudio/cststudio.github.io/" master:master
    #- curl -H 'Content-Type:text/plain' --data-binary @urls.txt "http://data.zz.baidu.com/urls?site=www.latelee.org&token=kJPSxFFYjnuj0PrS"
    - echo "\r\npush done"
  only:
    - master
